### ISSUE TITLE
Component directory?

### ISSUE THREAD

**Issue by attila-at-hyper** [hyperoslo/iOS-playbook#124]
We have a great team and have a lot of components, categories, etc. developed by the team members. However it's pretty difficult (especially for someone remote like me) to get to know them and to keep track of the new components added over time.

How about creating a chapter in the Playbook containing a list of those components, categories, etc. with a one sentence description for each, a contact person and a link to a Github repo? That way when you start developing something new, you could check the directory first to see if there is something you could build on top of? Each team member would add/update his/her components to/in this directory.

**Comment by 3lvis** [comment]
Hi Attila! It's an interesting idea, I know @jgorset and @zenangst have been discussing improving the http://opensource.hyper.no webpage to contain a list of things that we've made. 

Although for me this is just one of those things that you discuss with your team when the time comes, I'm not sure if the idea is to keep everything in the playbook in order for us to not "bother" the other team members. I'm ok with been "bothered" when it comes to talk about finding the best solution to a problem, is one of those things that keep me going. Most of the time the right tool might not even be something that we create but something that we saw, fits our needs and we could contribute too!

What do you guys think? @hyperoslo/ios

**Comment by jgorset** [comment]
I agree, @3lvis. I think this boils down to two things, @attila-at-hyper:

1. We could be better at telling the rest of @hyperoslo about the things we open source.
2. We could be better at remote.

To help with # 1, We're going to start taking a few minutes at general assembly to tell everyone about it when we make something awesome. We did this for Form a few weeks back and we're doing it for Sync this week or the next.

As for # 2, since we're running mostly everything at the general assemblies in English now anyway I think a nice next step would be to start live streaming them.

Oh, and opensource.hyper.no is definitely happening. I'll give it a shot this weekend and maybe show it to @thuygianguyen and his awesome friends for some pointers.

**Comment by attila-at-hyper** [comment]
@3lvis: you're most likely right, I'm just reluctant to "bother" others as opposed to trying to solve something on my own (for which I need more information at hand). Personally I believe to produce great results you need to remained focused, which is (at least for me) difficult when there are distractions (Slack messages, emails, etc.) to watch for/to be answered in every couple of minutes. Again, maybe it's just me, if so, my apologies. :)

@jgorset: hm, I don't recall attending the general assembly you mentioned. When was that? Such meetings could be great to announce and introduce major things (like Form and Sync), but I don't think they are the right forum to answer questions like "Do we have a solution to compare two strings containing version numbers to find out if one is 'newer' than the other?". To have such questions answered I usually use StackOverflow, but that doesn't help with internal resources.

**Comment by 3lvis** [comment]
@attila-at-hyper Feel free to resort to the team when facing issues, in this cases I feel I get better results after chatting about it with someone than on my own.

Is like having a second opinion, specially in things like this were you want to strive for reusability, the other person might have a different insight than yours because they are not as attached to the project.

Besides that we should totally have a list of the things that we've done. I made an issue for it.

https://github.com/hyperoslo/iOS-playbook/issues/125
