### ISSUE TITLE
API Design: Usage of closures and delegates

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/iOS-playbook#140]
For example in Form we have a lot of configuration blocks but I get the feeling that we should use delegates/dataSource instead. Makes API easier to follow and it's more clear to mark required and optional ones.

https://github.com/hyperoslo/Form/blob/master/Source/FORMDataSource.h#L14-L32

**Comment by kostiakoval** [comment]
Bad idea -> map, filter functions

**Comment by 3lvis** [comment]
For example in Form we have a lot of configuration blocks but I get the feeling that we should use delegates instead.

https://github.com/hyperoslo/Form/blob/master/Source/FORMDataSource.h#L14-L32

**Comment by 3lvis** [comment]
>Bad idea -> map, filter functions uses closures. 
and Closure is same as function

What does that has to do with API Design?

**Comment by kostiakoval** [comment]
map and filter functions is not asynchronous operation but they accept closures as a parameter

**Comment by 3lvis** [comment]
@kostiakoval This is specific to API design.

**Comment by kostiakoval** [comment]
Oh, I see you change the name ))) now it makes more sense and my comment is not valid than.
I agree it's confusing to chose between delegate and block.
I would try to list what is the difference between them.  in Swift closure and function is almost the same you can pass a function instead of a closure, so it look almost the same as delegate. 

Delegates:
- can be optional
- can handle many methods
- explicit receiver (you set a delegate)

Closures:
- Can be marked with nonnullable (not optional), In swift Optionals closures
- Can handle only 1 callback
- no receiver, jut a function to call, can be instance method

**Comment by 3lvis** [comment]
@kostiakoval https://github.com/hyperoslo/iOS-playbook/blob/master/BEST_PRACTICES.md#blocks-delegates-or-data-source

**Comment by onmyway133** [comment]
@3lvis Good points on when to use [Blocks, delegates or data source](https://github.com/hyperoslo/iOS-playbook/blob/master/BEST_PRACTICES.md#blocks-delegates-or-data-source).

I also like this [BLOCKS OR DELEGATES](http://blog.stablekernel.com/blocks-or-delegates/) on we can learn from Apple APIs :]

For me, it is also the matter of convenience. When I develop [Cine](https://github.com/onmyway133/Cine), as the number of callbacks increase, I changed from `block` to `delegate`

**Comment by 3lvis** [comment]
Closing old issues, since they might not be relevant.
