### ISSUE TITLE
Multiple return statements in methods

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/iOS-playbook#87]
I think having multiple returns in methods it's a bad pattern since I've faced that many bugs can be introduced in this way.

# Good
```objc
- (NSInteger)elementsCount
{
    NSInteger elementsCount;

    if (self.employee.hasChildren) {
        elementsCount = 3;
    } else if (self.employee.isSingle) {
        elementsCount = [self.employee numberOfRelatives];
    }

   return elementsCount;
}
```

# Bad
```objc
- (NSInteger)elementsCount
{
    if (self.employee.hasChildren) {
        return 3;
    } else if (self.employee.isSingle) {
        return [self.employee numberOfRelatives];
    }

   return 0;
}
```

**Comment by NSElvis** [comment]
@kostiakoval mentioned the [Golden Path](https://github.com/RobotsAndPencils/objective-c-style-guide#golden-path) but I think it's prone to exceptions and additional rules and I think that making our style guide simple would make it easy to follow.

Also it doesn't evolve nicely since you'll have to consider if your change breaks the Golden Path and that's one more thing that you have to worry about

**Comment by 3lvis** [comment]
Closing old issues, since they might not be relevant.
